# Site Info
title: Gudnam's Blog
tagline: 
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: http://gudnam.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Gudnam
  description: Android, Kotlin, Scala
  gravatar: 831427663b22cec1bae918fd07a7365e # md5 hash of your email address
  contact:
    github:    https://github.com/gudnam
    facebook:  https://www.facebook.com/profile.php?id=100001351858332&

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/squirrel.png
  caption: 

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-58713482-3' # leave blank if you don't want google analytics
disqus_short_name: 'gudnam' # leave blank if you don't want disqus

